### ISSUE TITLE
404 or empty PNG

### ISSUE THREAD

**Issue by j2l** [Fredi/DependencyGraph#1]
"http://yuml.me/diagram/class/" returns a 404 in program.cs. I changed it to http://yuml.me/diagram/scruffy/class/ and rebuilt it.
But now, "dg.exe C:\Users\pm\Downloads\DependencyGraph-master\DependencyGraph-master test.png" creates a 11x11 blank PNG
Any idea? Thanks!

**Comment by fredimachado** [comment]
Hi @j2l !

I fixed the dependency graph generation and updated it using the new yuml url, thanks for that.
This application generated graphics with project referencies only, that's why it did't work with itself (It only has assembly references).

I added an option to include assembly references too using the -i argument in the command line.
ex.: dg.exe C:\Project test.png -i

Hope it helps.

**Comment by j2l** [comment]
Hey. Sounds great! Thanks.
I'll test this tomorrow.
